# Generated by Django 5.2.17 on 2026-09-11 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('smp', 'SMP'), ('sma', 'SMA/SMK'), ('s1', 'S1')], default='s1', max_length=10)),
                ('major', models.CharField(blank=True, default='', max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
