# Generated by Django 5.2.17 on 2026-09-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
