# Generated by Django 5.2.17 on 2026-09-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_education_end_year_alter_education_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('smp', 'SMP'), ('sma', 'SMA/SMK'), ('s1', 'S1')], default='S1', max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.IntegerField(),
        ),
    ]
